export const BLE_SCAN_TIMEOUT_MS = 10000;
export const BLE_RECONNECT_DELAY_MS = 3000;
export const SESSION_SYNC_INTERVAL_MS = 5000;
export const VOICE_CONFIDENCE_MIN = 0.85;
export const CLIP_DETECT_CONFIDENCE = 0.75;
export const ZONE_THRESHOLD_SECONDS_DEFAULT = 10;
