"""
Auto-generated Fusion 360 CAM script.
Generated by aria_os/cam_generator.py

Part:     escape_wheel
Material: aluminium_6061
Bbox:     8.9 × 8.95 × 4.0 mm

HOW TO USE:
  1. In Fusion 360, open the STEP file: outputs\\cad\\step\\escape_wheel.step
  2. Go to Tools → Add-Ins → Scripts and Add-Ins
  3. Click + to add this script, then Run
  4. Toolpaths generate automatically. Review then post to gcode.
"""
import adsk.core
import adsk.fusion
import adsk.cam
import traceback

def run(context):
    ui = None
    try:
        app    = adsk.core.Application.get()
        ui     = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)

        # ── Switch to Manufacturing workspace ──────────────────────────────────
        camWs = ui.workspaces.itemById("CAMEnvironment")
        camWs.activate()

        cam = adsk.cam.CAM.cast(app.activeProduct)
        if cam is None:
            ui.messageBox("Could not get CAM object — ensure a part is open.")
            return

        # ── Create Setup ───────────────────────────────────────────────────────
        setups = cam.setups
        setupInput = setups.createInput(adsk.cam.OperationTypes.MillingOperation)

        # Setup orientation: top face up, origin at stock corner
        setupInput.stockMode = adsk.cam.SetupStockModes.FixedBoxStock
        boxStockInput = adsk.cam.FixedStockSizeInput.cast(setupInput.stock)
        boxStockInput.xOffset = adsk.core.ValueInput.createByReal(0.1)
        boxStockInput.yOffset = adsk.core.ValueInput.createByReal(0.1)
        boxStockInput.zOffset = adsk.core.ValueInput.createByReal(0.15)

        setup = setups.add(setupInput)
        setup.name = "escape_wheel_setup"

        # ── Build tool library entries ─────────────────────────────────────────
        toolLib = cam.documentToolLibrary

        def make_flat_endmill(name, dia_cm, flutes, rpm, feed_cmpm, plunge_cmpm):
            t = adsk.cam.ToolingData.createFlatMill()
            t.name          = name
            t.diameter      = adsk.core.ValueInput.createByReal(dia_cm)
            t.numberOfFlutes = flutes
            t.spindleSpeed  = adsk.core.ValueInput.createByReal(rpm)
            t.feedrate      = adsk.core.ValueInput.createByReal(feed_cmpm)
            t.plungeFeedrate = adsk.core.ValueInput.createByReal(plunge_cmpm)
            return toolLib.add(t)

        rough_tool    = make_flat_endmill(
            "1mm 2-flute carbide", 0.1, 2,
            24000, 28.8, 7.2
        )
        finish_tool   = make_flat_endmill(
            "1mm 2-flute carbide", 0.1, 2,
            24000, 28.8, 7.2
        )

        # ── Operation 1: 3D Adaptive Clearing (roughing) ──────────────────────
        adaptiveInput = setup.operations.createInput("adaptive")
        adaptiveInput.tool = rough_tool
        adaptiveInput.parameters.itemByName("optimalLoad").expression = "0.035"
        adaptiveInput.parameters.itemByName("maximumStepdown").expression = "0.05"
        adaptiveInput.parameters.itemByName("smoothingMode").expression = "true"
        adaptiveInput.parameters.itemByName("stockToLeave").expression = "0.03"  # 0.3mm stock
        adaptive_op = setup.operations.add(adaptiveInput)
        adaptive_op.name = "3D_Adaptive_Rough"

        # ── Operation 2: Parallel (scallop finishing) ──────────────────────────
        parallelInput = setup.operations.createInput("parallel")
        parallelInput.tool = finish_tool
        parallelInput.parameters.itemByName("stepover").expression = "0.01"
        parallelInput.parameters.itemByName("maximumStepdown").expression = "0.05"
        parallelInput.parameters.itemByName("stockToLeave").expression = "0"
        parallel_op = setup.operations.add(parallelInput)
        parallel_op.name = "Parallel_Finish"

        # ── Operation 3: Contour (edge finishing) ─────────────────────────────
        contourInput = setup.operations.createInput("contour")
        contourInput.tool = finish_tool
        contourInput.parameters.itemByName("stockToLeave").expression = "0"
        contour_op = setup.operations.add(contourInput)
        contour_op.name = "Contour_Edges"


        # Drill: M4 drill 3.3mm dia=3.3mm
        drillInput_0 = setup.operations.createInput("drill")
        drillInput_0.parameters.itemByName("cycleType").expression = "\"chip_breaking\""
        drill_op_0 = setup.operations.add(drillInput_0)
        drill_op_0.name = "Drill_3.3mm"


        # ── Generate and post toolpaths ────────────────────────────────────────
        # Generate all toolpaths
        cam.generateAllToolpaths(False)  # False = wait for completion

        # Post to gcode — uses Generic Milling post (swap for your machine post)
        postConfig  = cam.postConfigurations.itemByName("Generic Milling")
        outputFolder = r"C:\\Users\\jonko\\Downloads\\aria-auto-belay\\outputs\\cam\\escape_wheel\\gcode"
        postInput = adsk.cam.PostOutputUnitOptions.DocumentUnitsOutput
        if postConfig:
            cam.postProcess(setup, postConfig, outputFolder, postInput, "escape_wheel")
            ui.messageBox(f"CAM complete! Gcode saved to:\nC:\\Users\\jonko\\Downloads\\aria-auto-belay\\outputs\\cam\\escape_wheel\\gcode")
        else:
            ui.messageBox("Toolpaths generated. Select a post config to export gcode.")

    except Exception:
        if ui:
            ui.messageBox(f"CAM generation failed:\n{traceback.format_exc()}")
