# =============================================================================
# Fusion 360 constrained assembly script
# Generated by assemble_constrain.py
#
# Assembly : Mechanical Clock Gear Train
# Parts    : 32
# Joints   : 103
# Proximity: 50.0 mm
#
# HOW TO RUN
# ----------
#   1. Open Fusion 360 and create (or open) a design.
#   2. Tools > Scripts and Add-Ins > Scripts > "+" > browse to this file.
#   3. Click "Run".
#
# All STEP paths are embedded as absolute strings resolved at generation time.
# If you move files, update the STEP_PATHS dict below.
# =============================================================================

import adsk.core
import adsk.fusion
import math
import traceback

# ---------------------------------------------------------------------------
# STEP file paths (absolute at generation time)
# ---------------------------------------------------------------------------
STEP_PATHS = {
    "barrel_arbor": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/barrel_arbor.step",
    "barrel_drum": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/barrel_drum.step",
    "barrel_cap": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/barrel_cap.step",
    "barrel_wheel": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/barrel_wheel_96t.step",
    "click_wheel": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/click_wheel_16t.step",
    "center_arbor": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/center_arbor.step",
    "center_pinion": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/center_pinion_p8.step",
    "center_wheel": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/center_wheel_80t.step",
    "cannon_pinion": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/cannon_pinion_10t.step",
    "third_arbor": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/third_arbor.step",
    "third_pinion": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/third_pinion_p8.step",
    "third_wheel": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/third_wheel_48t.step",
    "fourth_arbor": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/fourth_arbor.step",
    "fourth_pinion": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/fourth_pinion_p8.step",
    "fourth_wheel": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/fourth_wheel_64t.step",
    "seconds_hand": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/seconds_hand.step",
    "escape_arbor": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/escape_arbor.step",
    "escape_pinion": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/escape_pinion_p8.step",
    "escape_wheel": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/escape_wheel_15t.step",
    "minute_wheel": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/minute_wheel_40t.step",
    "minute_pinion": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/minute_wheel_pinion_10t.step",
    "hour_wheel": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/hour_wheel_30t.step",
    "hour_hand": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/hour_hand.step",
    "minute_hand": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/minute_hand.step",
    "pillar_fl": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/pillar_x4.step",
    "pillar_fr": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/pillar_x4.step",
    "pillar_rl": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/pillar_x4.step",
    "pillar_rr": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/pillar_x4.step",
    "pendulum_rod": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/pendulum_rod.step",
    "pendulum_bob": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/pendulum_bob.step",
    "rating_nut": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/rating_nut.step",
    "dial_ring": r"C:/Users/jonko/Downloads/aria-auto-belay/outputs/cad/step/dial_ring.step",
}

def _make_transform(pos, rot_deg):
    """Build a Matrix3D from pos [mm] and rot [degrees, XYZ Euler]."""
    matrix = adsk.core.Matrix3D.create()
    rx, ry, rz = (math.radians(r) for r in rot_deg)
    cx, sx = math.cos(rx), math.sin(rx)
    cy, sy = math.cos(ry), math.sin(ry)
    cz, sz = math.cos(rz), math.sin(rz)
    r00 = cy * cz;          r01 = cy * sz;          r02 = -sy
    r10 = sx*sy*cz - cx*sz; r11 = sx*sy*sz + cx*cz; r12 = sx * cy
    r20 = cx*sy*cz + sx*sz; r21 = cx*sy*sz - sx*cz; r22 = cx * cy
    # Fusion internal units are cm — convert mm → cm
    tx, ty, tz = pos[0] / 10.0, pos[1] / 10.0, pos[2] / 10.0
    matrix.setWithArray([
        r00, r01, r02, tx,
        r10, r11, r12, ty,
        r20, r21, r22, tz,
        0,   0,   0,   1,
    ])
    return matrix



def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        design = app.activeProduct
        root = design.rootComponent
        import_mgr = app.importManager

        occurrences = {}  # part_id -> occurrence

        # ----------------------------------------------------------------
        # 1. Import STEP components
        # ----------------------------------------------------------------
        # --- barrel_arbor ---
        _step = STEP_PATHS['barrel_arbor']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([0, 0, 0], [0, 0, 0])
        occurrences['barrel_arbor'] = _occ

        # --- barrel_drum ---
        _step = STEP_PATHS['barrel_drum']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([0, 0, 5], [0, 0, 0])
        occurrences['barrel_drum'] = _occ

        # --- barrel_cap ---
        _step = STEP_PATHS['barrel_cap']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([0, 0, 17], [0, 0, 0])
        occurrences['barrel_cap'] = _occ

        # --- barrel_wheel ---
        _step = STEP_PATHS['barrel_wheel']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([0, 0, 25], [0, 0, 0])
        occurrences['barrel_wheel'] = _occ

        # --- click_wheel ---
        _step = STEP_PATHS['click_wheel']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([0, 0, 36], [0, 0, 0])
        occurrences['click_wheel'] = _occ

        # --- center_arbor ---
        _step = STEP_PATHS['center_arbor']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, 0, 0], [0, 0, 0])
        occurrences['center_arbor'] = _occ

        # --- center_pinion ---
        _step = STEP_PATHS['center_pinion']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, 0, 22], [0, 0, 0])
        occurrences['center_pinion'] = _occ

        # --- center_wheel ---
        _step = STEP_PATHS['center_wheel']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, 0, 32], [0, 0, 0])
        occurrences['center_wheel'] = _occ

        # --- cannon_pinion ---
        _step = STEP_PATHS['cannon_pinion']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, 0, 6], [0, 0, 0])
        occurrences['cannon_pinion'] = _occ

        # --- third_arbor ---
        _step = STEP_PATHS['third_arbor']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([122, 0, 0], [0, 0, 0])
        occurrences['third_arbor'] = _occ

        # --- third_pinion ---
        _step = STEP_PATHS['third_pinion']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([122, 0, 22], [0, 0, 0])
        occurrences['third_pinion'] = _occ

        # --- third_wheel ---
        _step = STEP_PATHS['third_wheel']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([122, 0, 32], [0, 0, 0])
        occurrences['third_wheel'] = _occ

        # --- fourth_arbor ---
        _step = STEP_PATHS['fourth_arbor']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([150, 0, 0], [0, 0, 0])
        occurrences['fourth_arbor'] = _occ

        # --- fourth_pinion ---
        _step = STEP_PATHS['fourth_pinion']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([150, 0, 22], [0, 0, 0])
        occurrences['fourth_pinion'] = _occ

        # --- fourth_wheel ---
        _step = STEP_PATHS['fourth_wheel']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([150, 0, 32], [0, 0, 0])
        occurrences['fourth_wheel'] = _occ

        # --- seconds_hand ---
        _step = STEP_PATHS['seconds_hand']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([150, 0, -3], [0, 0, 0])
        occurrences['seconds_hand'] = _occ

        # --- escape_arbor ---
        _step = STEP_PATHS['escape_arbor']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([186, 0, 0], [0, 0, 0])
        occurrences['escape_arbor'] = _occ

        # --- escape_pinion ---
        _step = STEP_PATHS['escape_pinion']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([186, 0, 22], [0, 0, 0])
        occurrences['escape_pinion'] = _occ

        # --- escape_wheel ---
        _step = STEP_PATHS['escape_wheel']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([186, 0, 32], [0, 0, 0])
        occurrences['escape_wheel'] = _occ

        # --- minute_wheel ---
        _step = STEP_PATHS['minute_wheel']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, -45, 6], [0, 0, 0])
        occurrences['minute_wheel'] = _occ

        # --- minute_pinion ---
        _step = STEP_PATHS['minute_pinion']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, -45, 10], [0, 0, 0])
        occurrences['minute_pinion'] = _occ

        # --- hour_wheel ---
        _step = STEP_PATHS['hour_wheel']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, 0, -2], [0, 0, 0])
        occurrences['hour_wheel'] = _occ

        # --- hour_hand ---
        _step = STEP_PATHS['hour_hand']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, 0, -6], [0, 0, 0])
        occurrences['hour_hand'] = _occ

        # --- minute_hand ---
        _step = STEP_PATHS['minute_hand']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, 0, -4], [0, 0, 0])
        occurrences['minute_hand'] = _occ

        # --- pillar_fl ---
        _step = STEP_PATHS['pillar_fl']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([0, 80, 30], [0, 0, 0])
        occurrences['pillar_fl'] = _occ

        # --- pillar_fr ---
        _step = STEP_PATHS['pillar_fr']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([186, 80, 30], [0, 0, 0])
        occurrences['pillar_fr'] = _occ

        # --- pillar_rl ---
        _step = STEP_PATHS['pillar_rl']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([0, -80, 30], [0, 0, 0])
        occurrences['pillar_rl'] = _occ

        # --- pillar_rr ---
        _step = STEP_PATHS['pillar_rr']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([186, -80, 30], [0, 0, 0])
        occurrences['pillar_rr'] = _occ

        # --- pendulum_rod ---
        _step = STEP_PATHS['pendulum_rod']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([186, 50, 25], [90, 0, 0])
        occurrences['pendulum_rod'] = _occ

        # --- pendulum_bob ---
        _step = STEP_PATHS['pendulum_bob']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([186, -198, 25], [0, 0, 0])
        occurrences['pendulum_bob'] = _occ

        # --- rating_nut ---
        _step = STEP_PATHS['rating_nut']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([186, -165, 25], [0, 0, 0])
        occurrences['rating_nut'] = _occ

        # --- dial_ring ---
        _step = STEP_PATHS['dial_ring']
        _opt = import_mgr.createSTEPImportOptions(_step)
        import_mgr.importToTarget(_opt, root)
        _occ = root.occurrences[-1]
        _occ.transform = _make_transform([78, 0, -8], [0, 0, 0])
        occurrences['dial_ring'] = _occ

        # ----------------------------------------------------------------
        # 2. As-built joints
        # ----------------------------------------------------------------
        # ----------------------------------------------------------------
        # As-built joints
        # ----------------------------------------------------------------

        # barrel_arbor <-> barrel_drum  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_arbor'], occurrences['barrel_drum'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # barrel_arbor <-> barrel_cap  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_arbor'], occurrences['barrel_cap'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # barrel_arbor <-> barrel_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_arbor'], occurrences['barrel_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # barrel_arbor <-> click_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_arbor'], occurrences['click_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # barrel_drum <-> barrel_cap  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_drum'], occurrences['barrel_cap'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # barrel_drum <-> barrel_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_drum'], occurrences['barrel_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # barrel_drum <-> click_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_drum'], occurrences['click_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # barrel_cap <-> barrel_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_cap'], occurrences['barrel_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # barrel_cap <-> click_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_cap'], occurrences['click_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # barrel_wheel <-> click_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['barrel_wheel'], occurrences['click_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> center_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['center_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> center_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['center_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> cannon_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['cannon_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> third_arbor  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['third_arbor'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> third_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['third_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> minute_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['minute_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> minute_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['minute_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> hour_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['hour_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> hour_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['hour_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> minute_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['minute_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_arbor <-> dial_ring  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_arbor'], occurrences['dial_ring'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> center_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['center_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> cannon_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['cannon_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> third_arbor  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['third_arbor'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> third_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['third_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> third_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['third_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> minute_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['minute_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> minute_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['minute_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> hour_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['hour_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> hour_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['hour_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> minute_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['minute_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_pinion <-> dial_ring  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_pinion'], occurrences['dial_ring'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_wheel <-> cannon_pinion  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_wheel'], occurrences['cannon_pinion'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_wheel <-> third_pinion  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['center_wheel'], occurrences['third_pinion'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # center_wheel <-> third_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_wheel'], occurrences['third_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_wheel <-> hour_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_wheel'], occurrences['hour_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_wheel <-> hour_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_wheel'], occurrences['hour_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_wheel <-> minute_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_wheel'], occurrences['minute_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # center_wheel <-> dial_ring  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['center_wheel'], occurrences['dial_ring'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # cannon_pinion <-> third_arbor  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['cannon_pinion'], occurrences['third_arbor'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # cannon_pinion <-> third_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['cannon_pinion'], occurrences['third_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # cannon_pinion <-> minute_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['cannon_pinion'], occurrences['minute_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # cannon_pinion <-> minute_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['cannon_pinion'], occurrences['minute_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # cannon_pinion <-> hour_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['cannon_pinion'], occurrences['hour_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # cannon_pinion <-> hour_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['cannon_pinion'], occurrences['hour_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # cannon_pinion <-> minute_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['cannon_pinion'], occurrences['minute_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # cannon_pinion <-> dial_ring  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['cannon_pinion'], occurrences['dial_ring'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> third_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['third_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> third_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['third_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> fourth_arbor  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['fourth_arbor'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> fourth_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['fourth_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> fourth_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['fourth_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> seconds_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['seconds_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> hour_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['hour_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> hour_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['hour_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> minute_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['minute_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_arbor <-> dial_ring  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_arbor'], occurrences['dial_ring'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_pinion <-> third_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['third_pinion'], occurrences['third_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # third_pinion <-> fourth_arbor  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_pinion'], occurrences['fourth_arbor'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_pinion <-> fourth_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_pinion'], occurrences['fourth_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_pinion <-> fourth_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['third_pinion'], occurrences['fourth_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # third_pinion <-> seconds_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_pinion'], occurrences['seconds_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_wheel <-> fourth_arbor  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['third_wheel'], occurrences['fourth_arbor'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # third_wheel <-> fourth_pinion  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['third_wheel'], occurrences['fourth_pinion'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # third_wheel <-> fourth_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_wheel'], occurrences['fourth_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # third_wheel <-> seconds_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['third_wheel'], occurrences['seconds_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # fourth_arbor <-> fourth_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_arbor'], occurrences['fourth_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # fourth_arbor <-> fourth_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_arbor'], occurrences['fourth_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # fourth_arbor <-> seconds_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_arbor'], occurrences['seconds_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # fourth_arbor <-> escape_arbor  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_arbor'], occurrences['escape_arbor'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # fourth_arbor <-> escape_pinion  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_arbor'], occurrences['escape_pinion'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # fourth_arbor <-> escape_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_arbor'], occurrences['escape_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # fourth_pinion <-> fourth_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_pinion'], occurrences['fourth_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # fourth_pinion <-> seconds_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_pinion'], occurrences['seconds_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # fourth_pinion <-> escape_arbor  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_pinion'], occurrences['escape_arbor'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # fourth_pinion <-> escape_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_pinion'], occurrences['escape_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # fourth_pinion <-> escape_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_pinion'], occurrences['escape_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # fourth_wheel <-> seconds_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_wheel'], occurrences['seconds_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # fourth_wheel <-> escape_arbor  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_wheel'], occurrences['escape_arbor'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # fourth_wheel <-> escape_pinion  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_wheel'], occurrences['escape_pinion'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # fourth_wheel <-> escape_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['fourth_wheel'], occurrences['escape_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # seconds_hand <-> escape_arbor  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['seconds_hand'], occurrences['escape_arbor'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # seconds_hand <-> escape_pinion  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['seconds_hand'], occurrences['escape_pinion'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # escape_arbor <-> escape_pinion  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['escape_arbor'], occurrences['escape_pinion'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # escape_arbor <-> escape_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['escape_arbor'], occurrences['escape_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # escape_pinion <-> escape_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['escape_pinion'], occurrences['escape_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # minute_wheel <-> minute_pinion  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_wheel'], occurrences['minute_pinion'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # minute_wheel <-> hour_wheel  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_wheel'], occurrences['hour_wheel'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # minute_wheel <-> hour_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_wheel'], occurrences['hour_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # minute_wheel <-> minute_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_wheel'], occurrences['minute_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # minute_wheel <-> dial_ring  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_wheel'], occurrences['dial_ring'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # minute_pinion <-> hour_wheel  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_pinion'], occurrences['hour_wheel'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # minute_pinion <-> hour_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_pinion'], occurrences['hour_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # minute_pinion <-> minute_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_pinion'], occurrences['minute_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # minute_pinion <-> dial_ring  [revolute, axis=z]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_pinion'], occurrences['dial_ring'], None)
        _ji.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
        root.asBuiltJoints.add(_ji)

        # hour_wheel <-> hour_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['hour_wheel'], occurrences['hour_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # hour_wheel <-> minute_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['hour_wheel'], occurrences['minute_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # hour_wheel <-> dial_ring  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['hour_wheel'], occurrences['dial_ring'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # hour_hand <-> minute_hand  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['hour_hand'], occurrences['minute_hand'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # hour_hand <-> dial_ring  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['hour_hand'], occurrences['dial_ring'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # minute_hand <-> dial_ring  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['minute_hand'], occurrences['dial_ring'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # pillar_fr <-> pendulum_rod  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['pillar_fr'], occurrences['pendulum_rod'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        # pendulum_bob <-> rating_nut  [rigid, axis=None]
        _ji = root.asBuiltJoints.createInput(occurrences['pendulum_bob'], occurrences['rating_nut'], None)
        _ji.setAsRigidJointMotion()
        root.asBuiltJoints.add(_ji)

        ui.messageBox(
            'Assembly complete!\n'
            'Name   : Mechanical Clock Gear Train\n'
            'Parts  : 32\n'
            'Joints : 103\n'
        )

    except:  # noqa: E722
        if ui:
            ui.messageBox('Error:\n' + traceback.format_exc())
