"""
Auto-generated Fusion 360 CAM script.
Generated by aria_os/agents/cam_agent.py (deterministic fallback)

Part:     llm_climbing_hold_bracket_m8_mounting
Material: aluminium_6061
Machine:  Generic VMC
Bbox:     80.0 x 6.0 x 60.0 mm

HOW TO USE:
  1. In Fusion 360, open the STEP file: C:\Users\jonko\Downloads\aria-auto-belay\outputs\cad\step\llm_climbing_hold_bracket_m8_mounting.step
  2. Go to Tools > Add-Ins > Scripts and Add-Ins
  3. Click + to add this script, then Run
  4. Toolpaths generate automatically. Review then post to gcode.
"""
import adsk.core
import adsk.fusion
import adsk.cam
import traceback


def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)

        # Switch to Manufacturing workspace
        camWs = ui.workspaces.itemById("CAMEnvironment")
        camWs.activate()

        cam = adsk.cam.CAM.cast(app.activeProduct)
        if cam is None:
            ui.messageBox("Could not get CAM object — ensure a part is open.")
            return

        # Create Setup
        setups = cam.setups
        setupInput = setups.createInput(adsk.cam.OperationTypes.MillingOperation)
        setupInput.stockMode = adsk.cam.SetupStockModes.FixedBoxStock
        boxStockInput = adsk.cam.FixedStockSizeInput.cast(setupInput.stock)
        boxStockInput.xOffset = adsk.core.ValueInput.createByReal(0.1)
        boxStockInput.yOffset = adsk.core.ValueInput.createByReal(0.1)
        boxStockInput.zOffset = adsk.core.ValueInput.createByReal(0.15)
        setup = setups.add(setupInput)
        setup.name = "llm_climbing_hold_bracket_m8_mounting_setup"

        # Tool library
        toolLib = cam.documentToolLibrary

        def _make_flat_mill(name, dia_cm, flutes, rpm, feed_cmpm, plunge_cmpm):
            t = adsk.cam.ToolingData.createFlatMill()
            t.name = name
            t.diameter = adsk.core.ValueInput.createByReal(dia_cm)
            t.numberOfFlutes = flutes
            t.spindleSpeed = adsk.core.ValueInput.createByReal(rpm)
            t.feedrate = adsk.core.ValueInput.createByReal(feed_cmpm)
            t.plungeFeedrate = adsk.core.ValueInput.createByReal(plunge_cmpm)
            return toolLib.add(t)

        def _make_ball_mill(name, dia_cm, flutes, rpm, feed_cmpm, plunge_cmpm):
            t = adsk.cam.ToolingData.createBallMill()
            t.name = name
            t.diameter = adsk.core.ValueInput.createByReal(dia_cm)
            t.numberOfFlutes = flutes
            t.spindleSpeed = adsk.core.ValueInput.createByReal(rpm)
            t.feedrate = adsk.core.ValueInput.createByReal(feed_cmpm)
            t.plungeFeedrate = adsk.core.ValueInput.createByReal(plunge_cmpm)
            return toolLib.add(t)

        def _make_drill(name, dia_cm):
            t = adsk.cam.ToolingData.createDrill()
            t.name = name
            t.diameter = adsk.core.ValueInput.createByReal(dia_cm)
            return toolLib.add(t)

        # Create tools
        # endmill: EM-3 dia=3.0mm 2fl
        tool_0 = _make_flat_mill("EM-3", 0.3, 2, 9702, 194.0, 48.5)
        # endmill: EM-3 dia=3.0mm 2fl
        tool_1 = _make_flat_mill("EM-3", 0.3, 2, 9702, 194.0, 48.5)
        # ball_nose: BN-6 dia=6.0mm 2fl
        tool_2 = _make_ball_mill("BN-6", 0.6, 2, 4851, 97.0, 24.2)
        # Drill: DR-8 dia=8.0mm
        tool_3 = _make_drill("DR-8", 0.8)

        # Create operations
        # Op 1: 3D Adaptive — EM-3, 9702 RPM, 1940 mm/min, 1.5mm DOC
        _inp = setup.operations.createInput("adaptive")
        _inp.tool = tool_1
        _inp.parameters.itemByName("optimalLoad").expression = "0.12"
        _inp.parameters.itemByName("maximumStepdown").expression = "0.15"
        _inp.parameters.itemByName("stockToLeave").expression = "0.03"
        _op_0 = setup.operations.add(_inp)
        _op_0.name = "3D_Adaptive_Rough"
        # Op 2: Parallel — EM-3, 9702 RPM, 1940 mm/min
        _inp = setup.operations.createInput("parallel")
        _inp.tool = tool_1
        _inp.parameters.itemByName("stepover").expression = "0.03"
        _inp.parameters.itemByName("maximumStepdown").expression = "0.05"
        _inp.parameters.itemByName("stockToLeave").expression = "0.0"
        _op_1 = setup.operations.add(_inp)
        _op_1.name = "Parallel_Finish"
        # Op 3: Contour — BN-6, 4851 RPM, 970 mm/min
        _inp = setup.operations.createInput("contour")
        _inp.tool = tool_2
        _inp.parameters.itemByName("stockToLeave").expression = "0.0"
        _op_2 = setup.operations.add(_inp)
        _op_2.name = "Contour_Walls"
        # Op 4: Drill — DR-8, 3638 RPM, peck 4.0mm
        _inp = setup.operations.createInput("drill")
        _inp.tool = tool_3
        _inp.parameters.itemByName("cycleType").expression = "\"chip_breaking\""
        _op_3 = setup.operations.add(_inp)
        _op_3.name = "Drill_8mm"

        # Generate all toolpaths
        cam.generateAllToolpaths(False)

        # Post to G-code
        postConfig = cam.postConfigurations.itemByName("Generic Milling")
        outputFolder = r"C:\\Users\\jonko\\Downloads\\aria-auto-belay\\outputs\\cam\\llm_climbing_hold_bracket_m8_mounting\\gcode"
        postInput = adsk.cam.PostOutputUnitOptions.DocumentUnitsOutput
        if postConfig:
            cam.postProcess(setup, postConfig, outputFolder, postInput, "llm_climbing_hold_bracket_m8_mounting")
            ui.messageBox(f"CAM complete! Gcode saved to:\nC:\\Users\\jonko\\Downloads\\aria-auto-belay\\outputs\\cam\\llm_climbing_hold_bracket_m8_mounting\\gcode")
        else:
            ui.messageBox("Toolpaths generated. Select a post config to export gcode.")

    except Exception:
        if ui:
            ui.messageBox(f"CAM generation failed:\n{traceback.format_exc()}")
