"""
Auto-generated KiCad pcbnew script.
Generated by aria_os/ecad_generator.py

Board:  aria_esp32_board_80x60mm_12v_uart_ble_hx711_vesc
Size:   80.0 x 60.0 mm

HOW TO USE:
  1. Open KiCad 7, create or open a project.
  2. Open PCB Editor (pcbnew).
  3. Tools → Scripting Console → paste or exec this file:
         exec(open(r"C:\\Users\\jonko\\Downloads\\aria-auto-belay\\outputs\\ecad\\aria_esp32_board_80x60mm_12v_uart_ble_hx711_vesc\\aria_esp32_board_80x60mm_12v_uart_ble_hx711_vesc_pcbnew.py").read())
  4. The board outline, footprints, mounting holes, and labels are added
     automatically.  Press Ctrl+Z to undo if needed.
"""
import pcbnew

# Firmware pin assignments (from aria_main.cpp / aria_esp32_firmware.ino):
# HREF_GPIO_NUM = 47
# PCLK_GPIO_NUM = 13
# PIN_AS5048_CS = PA4
# PIN_BRAKE = PB13
# PIN_EN = PB10
# PIN_ESTOP = PB12
# PIN_HX711_DOUT = PB0
# PIN_HX711_SCK = PB1
# PIN_LED = PC13
# PIN_UH = PA8
# PIN_VH = PA9
# PIN_WH = PA10
# SIOC_GPIO_NUM = 39
# SIOD_GPIO_NUM = 40
# VSYNC_GPIO_NUM = 38
# XCLK_GPIO_NUM = 10
# Y2_GPIO_NUM = 15
# Y3_GPIO_NUM = 17
# Y4_GPIO_NUM = 18
# Y5_GPIO_NUM = 16
# Y6_GPIO_NUM = 14
# Y7_GPIO_NUM = 12
# Y8_GPIO_NUM = 11
# Y9_GPIO_NUM = 48
BOARD_W_MM = 80.0
BOARD_H_MM = 60.0

board = pcbnew.GetBoard()

def mm(v):
    return pcbnew.FromMM(v)

# ── Board outline (Edge.Cuts) ──────────────────────────────────────────────────
def add_outline(board, w, h):
    corners = [(0, 0), (w, 0), (w, h), (0, h)]
    for i in range(4):
        x1, y1 = corners[i]
        x2, y2 = corners[(i + 1) % 4]
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetLayer(pcbnew.Edge_Cuts)
        seg.SetStart(pcbnew.VECTOR2I(mm(x1), mm(y1)))
        seg.SetEnd(pcbnew.VECTOR2I(mm(x2), mm(y2)))
        seg.SetWidth(mm(0.05))
        board.Add(seg)

add_outline(board, BOARD_W_MM, BOARD_H_MM)

# ── Mounting holes (M3, 4 corners, 3 mm from edge) ────────────────────────────
HOLE_OFFSET = 3.0
HOLE_DIA    = 3.2   # M3 clearance

def add_mounting_hole(board, x, y):
    fp = pcbnew.FOOTPRINT(board)
    fp.SetReference("MH")
    fp.SetValue("MountingHole_3.2mm")
    fp.SetPosition(pcbnew.VECTOR2I(mm(x), mm(y)))

    pad = pcbnew.PAD(fp)
    pad.SetShape(pcbnew.PAD_SHAPE_CIRCLE)
    pad.SetAttribute(pcbnew.PAD_ATTRIB_NPTH)
    pad.SetSize(pcbnew.VECTOR2I(mm(HOLE_DIA), mm(HOLE_DIA)))
    pad.SetDrillSize(pcbnew.VECTOR2I(mm(HOLE_DIA), mm(HOLE_DIA)))
    pad.SetPosition(pcbnew.VECTOR2I(mm(x), mm(y)))
    fp.Add(pad)
    board.Add(fp)

add_mounting_hole(board, HOLE_OFFSET,             HOLE_OFFSET)
add_mounting_hole(board, BOARD_W_MM - HOLE_OFFSET, HOLE_OFFSET)
add_mounting_hole(board, HOLE_OFFSET,             BOARD_H_MM - HOLE_OFFSET)
add_mounting_hole(board, BOARD_W_MM - HOLE_OFFSET, BOARD_H_MM - HOLE_OFFSET)

# ── Helper: add text label on silkscreen ──────────────────────────────────────
def silk_label(board, x, y, text, size_mm=1.0):
    t = pcbnew.PCB_TEXT(board)
    t.SetText(text)
    t.SetPosition(pcbnew.VECTOR2I(mm(x), mm(y)))
    t.SetLayer(pcbnew.F_SilkS)
    t.SetTextSize(pcbnew.VECTOR2I(mm(size_mm), mm(size_mm)))
    t.SetTextThickness(mm(0.15))
    board.Add(t)

# Board title label
silk_label(board, 2.0, BOARD_H_MM - 3.5, "aria_esp32_board_80x60mm_12v_uart_ble_hx711_vesc", size_mm=1.2)

# ── Helper: add footprint placeholder ─────────────────────────────────────────
def add_fp(board, ref, value, fp_id, x, y, desc=""):
    fp = pcbnew.FOOTPRINT(board)
    fp.SetReference(ref)
    fp.SetValue(value)
    fp.SetPosition(pcbnew.VECTOR2I(mm(x), mm(y)))
    # Silkscreen reference label
    silk_label(board, x, y - 1.5, ref, size_mm=0.8)
    board.Add(fp)
    return fp


# ── Components ───────────────────────────────────────────────────────────────
add_fp(board, "U1", "ESP32-S3-WROOM-1", "RF_Module:ESP32-S3-WROOM-1", 31.00, 14.50, "ESP32-S3 WiFi/BLE module")
add_fp(board, "J1", "Barrel-Jack-2.1mm", "Connector_BarrelJack:BarrelJack_Horizontal", 66.00, 5.00, "DC barrel jack (12-24 V input)")
add_fp(board, "U2", "AMS1117-3.3", "Package_TO_SOT_SMD:SOT-223-3_TabPin2", 52.00, 5.00, "3.3 V LDO regulator")
add_fp(board, "J2", "JST-XH-4P-UART", "Connector_JST:JST_XH_B4B-XH-A_1x04_P2.50mm_Vertical", 5.00, 5.00, "UART header (TX/RX/3V3/GND)")
add_fp(board, "ANT1", "BLE-Antenna-Keepout", "RF_Antenna:Antenna_Chip_TDK_ANT1608AI_0603", 0.00, 0.00, "BLE antenna keepout zone marker")
add_fp(board, "U3", "HX711", "Package_SO:SOIC-16_3.9x9.9mm_P1.27mm", 52.00, 13.50, "HX711 24-bit load cell ADC")
add_fp(board, "J3", "JST-XH-4P-LoadCell", "Connector_JST:JST_XH_B4B-XH-A_1x04_P2.50mm_Vertical", 5.00, 14.50, "Load cell connector (E+/E-/A+/A-)")
add_fp(board, "J4", "Molex-6P-Motor", "Connector_Molex:Molex_Mini-Fit_Jr_5566-06A2_2x03_P4.20mm_Vertical", 5.00, 24.00, "Motor / VESC 6-pin power connector")
add_fp(board, "C1", "100nF", "Capacitor_SMD:C_0402_1005Metric", 5.00, 51.00, "100 nF decoupling capacitor")
add_fp(board, "C2", "10uF", "Capacitor_SMD:C_0805_2012Metric", 8.00, 51.00, "10 µF bulk decoupling capacitor")
add_fp(board, "D1", "LED-Green", "LED_SMD:LED_0402_1005Metric", 12.00, 51.00, "Power indicator LED")
add_fp(board, "R1", "330R", "Resistor_SMD:R_0402_1005Metric", 15.00, 51.00, "LED current-limiting resistor")


# ── Refresh and save ───────────────────────────────────────────────────────────
pcbnew.Refresh()
board.Save(r"C:\\Users\\jonko\\Downloads\\aria-auto-belay\\outputs\\ecad\\aria_esp32_board_80x60mm_12v_uart_ble_hx711_vesc\\aria_esp32_board_80x60mm_12v_uart_ble_hx711_vesc.kicad_pcb")
print("[ecad] Saved:", r"C:\\Users\\jonko\\Downloads\\aria-auto-belay\\outputs\\ecad\\aria_esp32_board_80x60mm_12v_uart_ble_hx711_vesc\\aria_esp32_board_80x60mm_12v_uart_ble_hx711_vesc.kicad_pcb")
